api_version: 3
name: insider-detection-ai-training
description: Insider detection AI training project description file

participants:
  # change example.com to the FQDN of the server
  - name: overseer
    type: overseer
    org: upm
    protocol: https
    api_root: /api/v1
    port: 8443
  - name: localhost
    type: server
    org: upm
    fed_learn_port: 8002
    admin_port: 8003
  - name: site-1
    type: client
    org: upm
    # Specifying listening_host will enable the creation of one pair of
    # certificate/private key for this client, allowing the client to function
    # as a server for 3rd-party integration.
    # The value must be a hostname that the external trainer can reach via the network.
    # listening_host: site-1-lh
  - name: site-2
    type: client
    org: upm
  - name: rosa.llorente.alonso@alumnos.upm.es
    type: admin
    org: upm
    role: project_admin

# The same methods in all builders are called in their order defined in builders section
builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml
  - path: nvflare.lighter.impl.template.TemplateBuilder
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      config_folder: config
      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        # if overseer_exists is true, args here are ignored.  Provisioning
        #   tool will fill role, name and other local parameters automatically.
        # if overseer_exists is false, args in this section will be used.
        overseer_exists: false
        args:
           sp_end_point: localhost:8002:8003
           heartbeat_interval: 6 
  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder
