api_version: 3
name: insider-detection-ai-training
description: Insider detection AI training project description file

participants:
  # change example.com to the FQDN of the server
  - name: localhost
    type: server
    org: upm
    fed_learn_port: 8002
    admin_port: 8003
  - name: site-1
    type: client
    org: upm
    # Specifying listening_host will enable the creation of one pair of
    # certificate/private key for this client, allowing the client to function
    # as a server for 3rd-party integration.
    # The value must be a hostname that the external trainer can reach via the network.
    # listening_host: site-1-lh
  - name: site-2
    type: client
    org: upm
  - name: rosa.llorente.alonso@alumnos.upm.es
    type: admin
    org: upm
    role: project_admin

# The same methods in all builders are called in their order defined in builders section
builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml
  - path: nvflare.lighter.impl.template.TemplateBuilder
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      # config_folder can be set to inform upm FLARE where to get configuration
      config_folder: config
  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder
